sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '5'
  - '0.12'
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_script:
  - npm run coverage
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release

# whitelist
branches:
  only:
    - fork
